export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACTS_SEND = 'FETCH_CONTACTS_SEND';

export const FETCH_MORE_CONTACTS = 'FETCH_MORE_CONTACTS';
export const FETCH_MORE_CONTACTS_SEND = 'FETCH_MORE_CONTACTS_SEND';

export const RESET_CONTACTS = 'RESET_CONTACTS';
